server.port: 9000

spring:
  application.name: oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://d.0neteam.co.kr:8181/oauth
    username: user1
    password: user1
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      show_sql: true
      format_sql: true

logging.level.org:
    springframework.security: trace
    hibernate.sql: debug

rsa:
  public-key: classpath:keys/public.pem
  private-key: classpath:keys/private.pem
