server.port: 8000

spring:
  application.name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Allow-Credentials RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://172.0.0.1:5173
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
      routes:
        - id: stg-service
          uri: http://localhost:8001
          predicates:
            - Path=/stg/**
          filters:
            - RewritePath=/stg/?(?<segment>.*), /${segment}
            - ApiFilter
        - id: mfr-service
          uri: http://localhost:8002
          predicates:
            - Path=/mfr/**
          filters:
            - RewritePath=/mfr/?(?<segment>.*), /${segment}
            - ApiFilter
        - id: trs-service
          uri: http://localhost:8003
          predicates:
            - Path=/trs/**
          filters:
            - RewritePath=/trs/?(?<segment>.*), /${segment}
            - ApiFilter
        - id: oauth-service
          uri: http://localhost:9000
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/oauth/?(?<segment>.*), /${segment}
            - ApiFilter
        - id: openapi
          uri: http://localhost:8000
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
#        - id: react
#          uri: http://localhost:5173
#          predicates:
#            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: gateway
  tracing:
    enabled: false
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    use-root-path: true
#    path: /docs
    operationsSorter: method
    
logging.level.org.springframework: INFO
