server.port: 8002

spring:
  application.name: mfr
  datasource:
    stg:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://d.0neteam.co.kr:8181/stg
      username: user1
      password: user1
    mfr:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://d.0neteam.co.kr:8181/mfr
      username: user1
      password: user1
    trs:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://d.0neteam.co.kr:8181/trs
      username: user1
      password: user1
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      show_sql: true
      format_sql: true

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method

swagger:
  api-gateway-url: http://localhost:8000/${spring.application.name}

logging.level.org:
  springframework.security: trace
  hibernate.sql: debug

jwt:
  keys-uri: http://localhost:8000/oauth/.well-known/jwks.json
