server.port: 8001

spring:
  application.name: stg
  datasource:
    stg:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://d.0neteam.co.kr:8181/stg
      username: user1
      password: user1
    mfr:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://d.0neteam.co.kr:8181/mfr
      username: user1
      password: user1
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      show_sql: true
      format_sql: true

logging.level.org:
  springframework.security: trace
  hibernate.sql: debug

jwt:
  keys-uri: http://localhost:8000/app4/.well-known/jwks.json
